/**
 * Netflix Secret Genre Codes → TMDb API mapping
 *
 * Each entry maps a Netflix genre (with its secret code) to a TMDb
 * discover query so the app can fetch real content for that genre.
 *
 * Source codes: https://www.whats-on-netflix.com/news/the-netflix-id-bible-every-category-on-netflix/
 */
import { tmdb, type TMDBPage } from "@/lib/tmdb";

export interface NetflixGenre {
  id: number;           // Netflix secret code
  label: string;        // Display name
  emoji: string;
  colors: [string, string];   // gradient: top → bottom
  fetcher: (page: number) => Promise<TMDBPage>;
  parentId?: number;    // belongs to this parent group
}

export interface GenreGroup {
  id: number;
  label: string;
  emoji: string;
  colors: [string, string];
  subGenres: NetflixGenre[];
}

// ─── Top-level groups ──────────────────────────────────────────

export const GENRE_GROUPS: GenreGroup[] = [
  {
    id: 1365,
    label: "Action & Adventure",
    emoji: "⚡",
    colors: ["#C2130A", "#7A0000"],
    subGenres: [
      {
        id: 1365,
        label: "All Action & Adventure",
        emoji: "⚡",
        colors: ["#C2130A", "#7A0000"],
        fetcher: (p) => tmdb.discover("movie", 28, p),
      },
      {
        id: 43040,
        label: "Action Comedies",
        emoji: "🤣",
        colors: ["#E55B0A", "#8B2E00"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "28,35", sort_by: "popularity.desc" }, p),
      },
      {
        id: 1568,
        label: "Action Sci-Fi & Fantasy",
        emoji: "🚀",
        colors: ["#1D4ED8", "#7C3AED"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "28,878", sort_by: "popularity.desc" }, p),
      },
      {
        id: 43048,
        label: "Action Thrillers",
        emoji: "🔫",
        colors: ["#1E293B", "#0F172A"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "28,53", sort_by: "popularity.desc" }, p),
      },
      {
        id: 77232,
        label: "Asian Action Movies",
        emoji: "🥋",
        colors: ["#831843", "#500724"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 28, with_origin_country: "KR|JP|CN|TH", sort_by: "popularity.desc" }, p),
      },
      {
        id: 10118,
        label: "Classic Action & Adventure",
        emoji: "🎞️",
        colors: ["#78350F", "#431407"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 28, sort_by: "popularity.desc", "primary_release_date.lte": "1999-12-31" }, p),
      },
      {
        id: 9584,
        label: "Comic Book & Superhero",
        emoji: "🦸",
        colors: ["#1E40AF", "#1E3A5F"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_keywords: "9715|180547|9717", sort_by: "popularity.desc" }, p),
      },
      {
        id: 11828,
        label: "Crime Action & Adventure",
        emoji: "🚔",
        colors: ["#374151", "#111827"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "28,80", sort_by: "popularity.desc" }, p),
      },
      {
        id: 8985,
        label: "Martial Arts Movies",
        emoji: "🥷",
        colors: ["#164E63", "#0E3A4A"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_keywords: "10714|849", with_genres: 28, sort_by: "popularity.desc" }, p),
      },
      {
        id: 10702,
        label: "Military Action & Adventure",
        emoji: "🪖",
        colors: ["#365314", "#1A2E05"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "28,10752", sort_by: "popularity.desc" }, p),
      },
      {
        id: 7700,
        label: "Spy Action & Adventure",
        emoji: "🕵️",
        colors: ["#1E3A5F", "#172554"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_keywords: "10090|179431", with_genres: 28, sort_by: "popularity.desc" }, p),
      },
      {
        id: 47465,
        label: "Westerns",
        emoji: "🤠",
        colors: ["#92400E", "#78350F"],
        fetcher: (p) => tmdb.discover("movie", 37, p),
      },
    ],
  },
  {
    id: 7424,
    label: "Anime",
    emoji: "🎌",
    colors: ["#7B2FBE", "#4A1F9C"],
    subGenres: [
      {
        id: 7424,
        label: "All Anime",
        emoji: "🎌",
        colors: ["#7B2FBE", "#4A1F9C"],
        fetcher: (p) => tmdb.discoverWithParams("tv", { with_genres: 16, with_original_language: "ja", sort_by: "popularity.desc" }, p),
      },
      {
        id: 2653,
        label: "Anime Action",
        emoji: "⚔️",
        colors: ["#C2130A", "#7B2FBE"],
        fetcher: (p) => tmdb.discoverWithParams("tv", { with_genres: "16,28,10759", with_original_language: "ja", sort_by: "popularity.desc" }, p),
      },
      {
        id: 9302,
        label: "Anime Comedies",
        emoji: "😂",
        colors: ["#D97706", "#7B2FBE"],
        fetcher: (p) => tmdb.discoverWithParams("tv", { with_genres: "16,35", with_original_language: "ja", sort_by: "popularity.desc" }, p),
      },
      {
        id: 452,
        label: "Anime Dramas",
        emoji: "💔",
        colors: ["#6B21A8", "#3B0764"],
        fetcher: (p) => tmdb.discoverWithParams("tv", { with_genres: "16,18", with_original_language: "ja", sort_by: "popularity.desc" }, p),
      },
      {
        id: 11146,
        label: "Anime Fantasy",
        emoji: "🐉",
        colors: ["#1D4ED8", "#7B2FBE"],
        fetcher: (p) => tmdb.discoverWithParams("tv", { with_genres: "16,10765", with_original_language: "ja", sort_by: "popularity.desc" }, p),
      },
      {
        id: 3063,
        label: "Anime Features",
        emoji: "🎬",
        colors: ["#0F766E", "#7B2FBE"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 16, with_original_language: "ja", sort_by: "popularity.desc" }, p),
      },
      {
        id: 10695,
        label: "Anime Horror",
        emoji: "👻",
        colors: ["#1F2937", "#7B2FBE"],
        fetcher: (p) => tmdb.discoverWithParams("tv", { with_genres: "16,27", with_original_language: "ja", sort_by: "popularity.desc" }, p),
      },
      {
        id: 2729,
        label: "Anime Sci-Fi",
        emoji: "🤖",
        colors: ["#0369A1", "#7B2FBE"],
        fetcher: (p) => tmdb.discoverWithParams("tv", { with_genres: "16,10765", with_original_language: "ja", sort_by: "popularity.desc" }, p),
      },
      {
        id: 6721,
        label: "Anime Series",
        emoji: "📺",
        colors: ["#9333EA", "#4A1F9C"],
        fetcher: (p) => tmdb.discoverWithParams("tv", { with_genres: 16, with_original_language: "ja", sort_by: "vote_count.desc" }, p),
      },
    ],
  },
  {
    id: 783,
    label: "Children & Family",
    emoji: "👨‍👩‍👧",
    colors: ["#16A34A", "#14532D"],
    subGenres: [
      {
        id: 783,
        label: "All Family Movies",
        emoji: "👨‍👩‍👧",
        colors: ["#16A34A", "#14532D"],
        fetcher: (p) => tmdb.discover("movie", 10751, p),
      },
      {
        id: 6796,
        label: "Movies for Ages 0–4",
        emoji: "🍼",
        colors: ["#0EA5E9", "#0369A1"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 10751, certification_country: "US", certification: "G", sort_by: "popularity.desc" }, p),
      },
      {
        id: 5455,
        label: "Movies for Ages 5–7",
        emoji: "🧸",
        colors: ["#F59E0B", "#B45309"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "10751,16", sort_by: "popularity.desc" }, p),
      },
      {
        id: 561,
        label: "Movies for Ages 8–12",
        emoji: "🎒",
        colors: ["#10B981", "#047857"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "10751,12", sort_by: "popularity.desc" }, p),
      },
      {
        id: 67673,
        label: "Disney",
        emoji: "✨",
        colors: ["#1D4ED8", "#3730A3"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_companies: "2|3|4|5|6|420", sort_by: "popularity.desc" }, p),
      },
      {
        id: 27346,
        label: "Kids' TV",
        emoji: "📺",
        colors: ["#7C3AED", "#5B21B6"],
        fetcher: (p) => tmdb.discoverWithParams("tv", { with_genres: 10762, sort_by: "popularity.desc" }, p),
      },
      {
        id: 11177,
        label: "TV Cartoons",
        emoji: "🎨",
        colors: ["#EC4899", "#9D174D"],
        fetcher: (p) => tmdb.discoverWithParams("tv", { with_genres: "16,10762", sort_by: "popularity.desc" }, p),
      },
    ],
  },
  {
    id: 6548,
    label: "Comedies",
    emoji: "😂",
    colors: ["#D97706", "#92400E"],
    subGenres: [
      {
        id: 6548,
        label: "All Comedies",
        emoji: "😂",
        colors: ["#D97706", "#92400E"],
        fetcher: (p) => tmdb.discover("movie", 35, p),
      },
      {
        id: 869,
        label: "Dark Comedies",
        emoji: "😈",
        colors: ["#374151", "#1F2937"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "35,27", sort_by: "popularity.desc" }, p),
      },
      {
        id: 4426,
        label: "Foreign Comedies",
        emoji: "🌍",
        colors: ["#0D9488", "#134E4A"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 35, without_original_language: "en", sort_by: "popularity.desc" }, p),
      },
      {
        id: 89585,
        label: "Horror Comedies",
        emoji: "🧟",
        colors: ["#4B0082", "#1F2937"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "35,27", sort_by: "popularity.desc" }, p),
      },
      {
        id: 13335,
        label: "Musical Comedies",
        emoji: "🎵",
        colors: ["#DB2777", "#831843"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "35,10402", sort_by: "popularity.desc" }, p),
      },
      {
        id: 5475,
        label: "Romantic Comedies",
        emoji: "💕",
        colors: ["#F43F5E", "#9F1239"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "35,10749", sort_by: "popularity.desc" }, p),
      },
      {
        id: 11559,
        label: "Stand-up Comedy",
        emoji: "🎤",
        colors: ["#7C3AED", "#4C1D95"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 35, with_keywords: "9799|158718", sort_by: "popularity.desc" }, p),
      },
      {
        id: 3519,
        label: "Teen Comedies",
        emoji: "🧑‍🎓",
        colors: ["#0EA5E9", "#075985"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "35,18", certification_country: "US", "certification.lte": "PG-13", sort_by: "popularity.desc" }, p),
      },
    ],
  },
  {
    id: 6839,
    label: "Documentaries",
    emoji: "📽️",
    colors: ["#0369A1", "#0C4A6E"],
    subGenres: [
      {
        id: 6839,
        label: "All Documentaries",
        emoji: "📽️",
        colors: ["#0369A1", "#0C4A6E"],
        fetcher: (p) => tmdb.discover("movie", 99, p),
      },
      {
        id: 3652,
        label: "Biographical Documentaries",
        emoji: "🧑",
        colors: ["#1D4ED8", "#1E3A5F"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 99, with_keywords: "1402", sort_by: "popularity.desc" }, p),
      },
      {
        id: 9875,
        label: "Crime Documentaries",
        emoji: "🔍",
        colors: ["#1F2937", "#111827"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "99,80", sort_by: "popularity.desc" }, p),
      },
      {
        id: 5349,
        label: "Historical Documentaries",
        emoji: "📜",
        colors: ["#78350F", "#431407"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "99,36", sort_by: "popularity.desc" }, p),
      },
      {
        id: 90361,
        label: "Music & Concert Docs",
        emoji: "🎸",
        colors: ["#6D28D9", "#4C1D95"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "99,10402", sort_by: "popularity.desc" }, p),
      },
      {
        id: 2595,
        label: "Science & Nature Docs",
        emoji: "🔬",
        colors: ["#059669", "#064E3B"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 99, with_keywords: "196871|157355|225803", sort_by: "popularity.desc" }, p),
      },
      {
        id: 180,
        label: "Sports Documentaries",
        emoji: "🏆",
        colors: ["#047857", "#064E3B"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "99,18", with_keywords: "5286|157416", sort_by: "popularity.desc" }, p),
      },
      {
        id: 1159,
        label: "Travel & Adventure Docs",
        emoji: "✈️",
        colors: ["#0891B2", "#155E75"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "99,12", sort_by: "popularity.desc" }, p),
      },
    ],
  },
  {
    id: 5763,
    label: "Dramas",
    emoji: "🎭",
    colors: ["#6B21A8", "#3B0764"],
    subGenres: [
      {
        id: 5763,
        label: "All Dramas",
        emoji: "🎭",
        colors: ["#6B21A8", "#3B0764"],
        fetcher: (p) => tmdb.discover("movie", 18, p),
      },
      {
        id: 3179,
        label: "Biographical Dramas",
        emoji: "🧑",
        colors: ["#4338CA", "#312E81"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 18, with_keywords: "1402|6898", sort_by: "popularity.desc" }, p),
      },
      {
        id: 6889,
        label: "Crime Dramas",
        emoji: "🔫",
        colors: ["#374151", "#1F2937"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "18,80", sort_by: "popularity.desc" }, p),
      },
      {
        id: 3653,
        label: "Dramas Based on Real Life",
        emoji: "📖",
        colors: ["#92400E", "#78350F"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 18, with_keywords: "10683|818|14602", sort_by: "popularity.desc" }, p),
      },
      {
        id: 500,
        label: "LGBT+ Dramas",
        emoji: "🌈",
        colors: ["#DB2777", "#9D174D"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 18, with_keywords: "158718|262292|3074", sort_by: "popularity.desc" }, p),
      },
      {
        id: 1255,
        label: "Romantic Dramas",
        emoji: "💔",
        colors: ["#BE185D", "#831843"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "18,10749", sort_by: "popularity.desc" }, p),
      },
      {
        id: 7243,
        label: "Sports Dramas",
        emoji: "🏅",
        colors: ["#15803D", "#14532D"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "18,28", with_keywords: "5286|4282", sort_by: "popularity.desc" }, p),
      },
    ],
  },
  {
    id: 78367,
    label: "Foreign Movies",
    emoji: "🌍",
    colors: ["#0D9488", "#134E4A"],
    subGenres: [
      {
        id: 78367,
        label: "All Foreign Movies",
        emoji: "🌍",
        colors: ["#0D9488", "#134E4A"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { without_original_language: "en", sort_by: "popularity.desc" }, p),
      },
      {
        id: 10463,
        label: "Indian Movies",
        emoji: "🇮🇳",
        colors: ["#FF9933", "#138808"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_original_language: "hi|ta|te|ml|kn", sort_by: "popularity.desc" }, p),
      },
      {
        id: 5685,
        label: "Korean Movies",
        emoji: "🇰🇷",
        colors: ["#0052A5", "#C60C30"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_original_language: "ko", sort_by: "popularity.desc" }, p),
      },
      {
        id: 10398,
        label: "Japanese Movies",
        emoji: "🇯🇵",
        colors: ["#BC002D", "#1F2937"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_original_language: "ja", sort_by: "popularity.desc" }, p),
      },
      {
        id: 3960,
        label: "Chinese Movies",
        emoji: "🇨🇳",
        colors: ["#DE2910", "#8B0000"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_original_language: "zh", sort_by: "popularity.desc" }, p),
      },
      {
        id: 58807,
        label: "French Movies",
        emoji: "🇫🇷",
        colors: ["#002395", "#1F2937"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_original_language: "fr", sort_by: "popularity.desc" }, p),
      },
      {
        id: 58886,
        label: "German Movies",
        emoji: "🇩🇪",
        colors: ["#374151", "#1F2937"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_original_language: "de", sort_by: "popularity.desc" }, p),
      },
      {
        id: 10757,
        label: "British Movies",
        emoji: "🇬🇧",
        colors: ["#012169", "#C8102E"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_origin_country: "GB", sort_by: "popularity.desc" }, p),
      },
      {
        id: 58741,
        label: "Spanish Movies",
        emoji: "🇪🇸",
        colors: ["#AA151B", "#F1BF00"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_original_language: "es", sort_by: "popularity.desc" }, p),
      },
      {
        id: 8221,
        label: "Italian Movies",
        emoji: "🇮🇹",
        colors: ["#009246", "#CE2B37"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_original_language: "it", sort_by: "popularity.desc" }, p),
      },
      {
        id: 107570,
        label: "Thai Movies & TV",
        emoji: "🇹🇭",
        colors: ["#A51931", "#2D2A4A"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_original_language: "th", sort_by: "popularity.desc" }, p),
      },
      {
        id: 1613,
        label: "Latin American Movies",
        emoji: "💃",
        colors: ["#B91C1C", "#7F1D1D"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_original_language: "es|pt", with_origin_country: "MX|BR|AR|CO|CL", sort_by: "popularity.desc" }, p),
      },
    ],
  },
  {
    id: 8711,
    label: "Horror Movies",
    emoji: "😱",
    colors: ["#7F1D1D", "#1F2937"],
    subGenres: [
      {
        id: 8711,
        label: "All Horror",
        emoji: "😱",
        colors: ["#7F1D1D", "#1F2937"],
        fetcher: (p) => tmdb.discover("movie", 27, p),
      },
      {
        id: 10944,
        label: "Cult Horror Movies",
        emoji: "💀",
        colors: ["#1F2937", "#111827"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 27, sort_by: "vote_average.desc", "vote_count.gte": 500 }, p),
      },
      {
        id: 89585,
        label: "Horror Comedy",
        emoji: "🧟‍♀️",
        colors: ["#374151", "#7F1D1D"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "27,35", sort_by: "popularity.desc" }, p),
      },
      {
        id: 947,
        label: "Monster Movies",
        emoji: "👾",
        colors: ["#065F46", "#064E3B"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 27, with_keywords: "12554|11167|4379", sort_by: "popularity.desc" }, p),
      },
      {
        id: 8646,
        label: "Slasher & Serial Killer",
        emoji: "🔪",
        colors: ["#991B1B", "#450A0A"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 27, with_keywords: "11934|181677|203", sort_by: "popularity.desc" }, p),
      },
      {
        id: 42023,
        label: "Supernatural Horror",
        emoji: "👁️",
        colors: ["#312E81", "#1E1B4B"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 27, with_keywords: "10291|4379|11", sort_by: "popularity.desc" }, p),
      },
      {
        id: 52147,
        label: "Teen Screams",
        emoji: "🧟",
        colors: ["#7C3AED", "#4C1D95"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 27, certification_country: "US", "certification.lte": "PG-13", sort_by: "popularity.desc" }, p),
      },
      {
        id: 75804,
        label: "Vampire Horror",
        emoji: "🧛",
        colors: ["#4C0519", "#7F1D1D"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 27, with_keywords: "1299|234", sort_by: "popularity.desc" }, p),
      },
      {
        id: 75405,
        label: "Zombie Horror",
        emoji: "🧟‍♂️",
        colors: ["#166534", "#14532D"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 27, with_keywords: "12377|11612|6165", sort_by: "popularity.desc" }, p),
      },
    ],
  },
  {
    id: 8883,
    label: "Romantic Movies",
    emoji: "💕",
    colors: ["#BE185D", "#831843"],
    subGenres: [
      {
        id: 8883,
        label: "All Romance",
        emoji: "💕",
        colors: ["#BE185D", "#831843"],
        fetcher: (p) => tmdb.discover("movie", 10749, p),
      },
      {
        id: 5475,
        label: "Romantic Comedies",
        emoji: "😍",
        colors: ["#F43F5E", "#BE185D"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "10749,35", sort_by: "popularity.desc" }, p),
      },
      {
        id: 1255,
        label: "Romantic Dramas",
        emoji: "💔",
        colors: ["#9D174D", "#831843"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "10749,18", sort_by: "popularity.desc" }, p),
      },
      {
        id: 36103,
        label: "Quirky Romance",
        emoji: "🌀",
        colors: ["#7C3AED", "#BE185D"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "10749,35", sort_by: "vote_average.desc", "vote_count.gte": 100 }, p),
      },
      {
        id: 35800,
        label: "Steamy Romantic Movies",
        emoji: "🌹",
        colors: ["#7F1D1D", "#9D174D"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 10749, certification_country: "US", "certification.gte": "R", sort_by: "popularity.desc" }, p),
      },
      {
        id: 7153,
        label: "Romantic Foreign Movies",
        emoji: "🌍",
        colors: ["#0D9488", "#831843"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 10749, without_original_language: "en", sort_by: "popularity.desc" }, p),
      },
    ],
  },
  {
    id: 1492,
    label: "Sci-Fi & Fantasy",
    emoji: "🚀",
    colors: ["#1D4ED8", "#7C3AED"],
    subGenres: [
      {
        id: 1492,
        label: "All Sci-Fi & Fantasy",
        emoji: "🚀",
        colors: ["#1D4ED8", "#7C3AED"],
        fetcher: (p) => tmdb.discover("movie", 878, p),
      },
      {
        id: 3327,
        label: "Alien Sci-Fi",
        emoji: "👽",
        colors: ["#065F46", "#1D4ED8"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 878, with_keywords: "83|189985|3268", sort_by: "popularity.desc" }, p),
      },
      {
        id: 9744,
        label: "Fantasy Movies",
        emoji: "🧙",
        colors: ["#7C3AED", "#4C1D95"],
        fetcher: (p) => tmdb.discover("movie", 14, p),
      },
      {
        id: 6926,
        label: "Sci-Fi Adventure",
        emoji: "🌌",
        colors: ["#1D4ED8", "#0C4A6E"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "878,12", sort_by: "popularity.desc" }, p),
      },
      {
        id: 3916,
        label: "Sci-Fi Dramas",
        emoji: "🌠",
        colors: ["#1E3A5F", "#312E81"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "878,18", sort_by: "popularity.desc" }, p),
      },
      {
        id: 1694,
        label: "Sci-Fi Horror",
        emoji: "👾",
        colors: ["#1F2937", "#7C3AED"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "878,27", sort_by: "popularity.desc" }, p),
      },
      {
        id: 11014,
        label: "Sci-Fi Thrillers",
        emoji: "⚡",
        colors: ["#1E293B", "#1D4ED8"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "878,53", sort_by: "popularity.desc" }, p),
      },
      {
        id: 4734,
        label: "Cult Sci-Fi & Fantasy",
        emoji: "🛸",
        colors: ["#6D28D9", "#1D4ED8"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 878, sort_by: "vote_average.desc", "vote_count.gte": 1000 }, p),
      },
    ],
  },
  {
    id: 8933,
    label: "Thrillers",
    emoji: "😰",
    colors: ["#1E3A5F", "#0F172A"],
    subGenres: [
      {
        id: 8933,
        label: "All Thrillers",
        emoji: "😰",
        colors: ["#1E3A5F", "#0F172A"],
        fetcher: (p) => tmdb.discover("movie", 53, p),
      },
      {
        id: 10499,
        label: "Crime Thrillers",
        emoji: "🔍",
        colors: ["#1F2937", "#111827"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "53,80", sort_by: "popularity.desc" }, p),
      },
      {
        id: 31851,
        label: "Gangster Movies",
        emoji: "🕴️",
        colors: ["#374151", "#1F2937"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "53,80", with_keywords: "10349|2263|2235", sort_by: "popularity.desc" }, p),
      },
      {
        id: 9994,
        label: "Mysteries",
        emoji: "🔎",
        colors: ["#1E293B", "#0F172A"],
        fetcher: (p) => tmdb.discover("movie", 9648, p),
      },
      {
        id: 10504,
        label: "Political Thrillers",
        emoji: "🏛️",
        colors: ["#1E40AF", "#1E3A5F"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "53,18", with_keywords: "1714|175067|10210", sort_by: "popularity.desc" }, p),
      },
      {
        id: 5505,
        label: "Psychological Thrillers",
        emoji: "🧠",
        colors: ["#312E81", "#1E1B4B"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 53, with_keywords: "10084|11331", sort_by: "popularity.desc" }, p),
      },
      {
        id: 9147,
        label: "Spy Thrillers",
        emoji: "🕵️",
        colors: ["#0C4A6E", "#0F172A"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 53, with_keywords: "10090|179431", sort_by: "popularity.desc" }, p),
      },
      {
        id: 11140,
        label: "Supernatural Thrillers",
        emoji: "👁️",
        colors: ["#3B0764", "#1E1B4B"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "53,27", with_keywords: "10291|11", sort_by: "popularity.desc" }, p),
      },
    ],
  },
  {
    id: 83,
    label: "TV Shows",
    emoji: "📺",
    colors: ["#EA580C", "#7C2D12"],
    subGenres: [
      {
        id: 83,
        label: "All TV Shows",
        emoji: "📺",
        colors: ["#EA580C", "#7C2D12"],
        fetcher: (p) => tmdb.popularTV(p),
      },
      {
        id: 52117,
        label: "British TV Shows",
        emoji: "🇬🇧",
        colors: ["#012169", "#C8102E"],
        fetcher: (p) => tmdb.discoverWithParams("tv", { with_origin_country: "GB", sort_by: "popularity.desc" }, p),
      },
      {
        id: 26146,
        label: "Crime TV Shows",
        emoji: "🚔",
        colors: ["#1F2937", "#111827"],
        fetcher: (p) => tmdb.discoverWithParams("tv", { with_genres: "80,18", sort_by: "popularity.desc" }, p),
      },
      {
        id: 79936,
        label: "Korean TV Shows",
        emoji: "🇰🇷",
        colors: ["#1D4ED8", "#1E3A5F"],
        fetcher: (p) => tmdb.koreanDramas(p),
      },
      {
        id: 4814,
        label: "Miniseries",
        emoji: "🎬",
        colors: ["#6D28D9", "#4C1D95"],
        fetcher: (p) => tmdb.discoverWithParams("tv", { with_type: 2, sort_by: "popularity.desc" }, p),
      },
      {
        id: 9833,
        label: "Reality TV",
        emoji: "🎭",
        colors: ["#D97706", "#92400E"],
        fetcher: (p) => tmdb.discoverWithParams("tv", { with_genres: 10764, sort_by: "popularity.desc" }, p),
      },
      {
        id: 1372,
        label: "TV Sci-Fi & Fantasy",
        emoji: "🛸",
        colors: ["#1D4ED8", "#7C3AED"],
        fetcher: (p) => tmdb.scifiFantasyTV(p),
      },
      {
        id: 10673,
        label: "TV Action & Adventure",
        emoji: "⚔️",
        colors: ["#C2130A", "#7A0000"],
        fetcher: (p) => tmdb.discoverWithParams("tv", { with_genres: 10759, sort_by: "popularity.desc" }, p),
      },
      {
        id: 11714,
        label: "TV Dramas",
        emoji: "🎭",
        colors: ["#6B21A8", "#3B0764"],
        fetcher: (p) => tmdb.discoverWithParams("tv", { with_genres: 18, sort_by: "popularity.desc" }, p),
      },
      {
        id: 83059,
        label: "TV Horror",
        emoji: "😱",
        colors: ["#7F1D1D", "#1F2937"],
        fetcher: (p) => tmdb.discoverWithParams("tv", { with_genres: 27, sort_by: "popularity.desc" }, p),
      },
    ],
  },
  {
    id: 4370,
    label: "Sports Movies",
    emoji: "🏆",
    colors: ["#15803D", "#14532D"],
    subGenres: [
      {
        id: 4370,
        label: "All Sports",
        emoji: "🏆",
        colors: ["#15803D", "#14532D"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 18, with_keywords: "5286|4282|17582", sort_by: "popularity.desc" }, p),
      },
      {
        id: 12762,
        label: "Basketball Movies",
        emoji: "🏀",
        colors: ["#EA580C", "#7C2D12"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_keywords: "6256|12762", sort_by: "popularity.desc" }, p),
      },
      {
        id: 12443,
        label: "Boxing Movies",
        emoji: "🥊",
        colors: ["#B91C1C", "#7F1D1D"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_keywords: "1612|12443|2169", sort_by: "popularity.desc" }, p),
      },
      {
        id: 12803,
        label: "Football Movies",
        emoji: "⚽",
        colors: ["#15803D", "#065F46"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_keywords: "12803|6256|6561", sort_by: "popularity.desc" }, p),
      },
      {
        id: 12339,
        label: "Baseball Movies",
        emoji: "⚾",
        colors: ["#1D4ED8", "#1E3A5F"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_keywords: "12339|6256|4682", sort_by: "popularity.desc" }, p),
      },
      {
        id: 7243,
        label: "Sports Dramas",
        emoji: "🏅",
        colors: ["#6B21A8", "#14532D"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 18, with_keywords: "5286|4282", sort_by: "vote_average.desc", "vote_count.gte": 200 }, p),
      },
    ],
  },
  {
    id: 1701,
    label: "Music",
    emoji: "🎵",
    colors: ["#9333EA", "#6B21A8"],
    subGenres: [
      {
        id: 1701,
        label: "All Music",
        emoji: "🎵",
        colors: ["#9333EA", "#6B21A8"],
        fetcher: (p) => tmdb.discover("movie", 10402, p),
      },
      {
        id: 3278,
        label: "Rock & Pop Concerts",
        emoji: "🎸",
        colors: ["#B91C1C", "#6B21A8"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 10402, with_keywords: "1299|2651", sort_by: "popularity.desc" }, p),
      },
      {
        id: 13335,
        label: "Musicals",
        emoji: "🎭",
        colors: ["#DB2777", "#9333EA"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "10402,35", sort_by: "popularity.desc" }, p),
      },
      {
        id: 10271,
        label: "Jazz & Easy Listening",
        emoji: "🎷",
        colors: ["#1E3A5F", "#6B21A8"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 10402, with_keywords: "3676|1500", sort_by: "vote_average.desc" }, p),
      },
    ],
  },
  {
    id: 5977,
    label: "LGBTQ+",
    emoji: "🌈",
    colors: ["#EC4899", "#7C3AED"],
    subGenres: [
      {
        id: 5977,
        label: "All LGBTQ+",
        emoji: "🌈",
        colors: ["#EC4899", "#7C3AED"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_keywords: "158718|262292|3074|9715|182468", sort_by: "popularity.desc" }, p),
      },
      {
        id: 7120,
        label: "LGBTQ+ Comedies",
        emoji: "😄",
        colors: ["#F59E0B", "#EC4899"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 35, with_keywords: "158718|262292|3074", sort_by: "popularity.desc" }, p),
      },
      {
        id: 4720,
        label: "LGBTQ+ Documentaries",
        emoji: "📽️",
        colors: ["#0EA5E9", "#EC4899"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 99, with_keywords: "158718|262292|3074", sort_by: "popularity.desc" }, p),
      },
      {
        id: 500,
        label: "LGBTQ+ Dramas",
        emoji: "🎭",
        colors: ["#6B21A8", "#EC4899"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 18, with_keywords: "158718|262292|3074", sort_by: "popularity.desc" }, p),
      },
      {
        id: 65263,
        label: "LGBTQ+ TV Shows",
        emoji: "📺",
        colors: ["#7C3AED", "#EC4899"],
        fetcher: (p) => tmdb.discoverWithParams("tv", { with_keywords: "158718|262292|3074", sort_by: "popularity.desc" }, p),
      },
    ],
  },
  {
    id: 31574,
    label: "Classic Movies",
    emoji: "🎞️",
    colors: ["#78350F", "#292524"],
    subGenres: [
      {
        id: 31574,
        label: "All Classic Movies",
        emoji: "🎞️",
        colors: ["#78350F", "#292524"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { sort_by: "vote_average.desc", "vote_count.gte": 2000, "primary_release_date.lte": "1999-12-31" }, p),
      },
      {
        id: 31694,
        label: "Classic Comedies",
        emoji: "😂",
        colors: ["#D97706", "#78350F"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 35, "primary_release_date.lte": "1999-12-31", sort_by: "vote_average.desc", "vote_count.gte": 500 }, p),
      },
      {
        id: 29809,
        label: "Classic Dramas",
        emoji: "🎭",
        colors: ["#6B21A8", "#78350F"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: 18, "primary_release_date.lte": "1989-12-31", sort_by: "vote_average.desc", "vote_count.gte": 500 }, p),
      },
      {
        id: 7687,
        label: "Film Noir",
        emoji: "🕵️",
        colors: ["#1C1917", "#292524"],
        fetcher: (p) => tmdb.discoverWithParams("movie", { with_genres: "53,80", "primary_release_date.lte": "1969-12-31", sort_by: "vote_average.desc" }, p),
      },
    ],
  },
];

// Flat lookup by Netflix ID
export const GENRE_BY_ID = new Map<number, NetflixGenre>(
  GENRE_GROUPS.flatMap((g) => g.subGenres.map((s) => [s.id, s]))
);

export const GROUP_BY_ID = new Map<number, GenreGroup>(
  GENRE_GROUPS.map((g) => [g.id, g])
);
