/**
 * S-MOVIE Source Catalog — 94 Sources (live count: ALL_SOURCES.length)
 *
 * Master registry of every streaming, anime, manga, and live-sports source.
 * Categories:
 *   movies      — general movie/show streaming sites
 *   anime       — dedicated anime streaming platforms
 *   manga       — manga / comic reading portals
 *   live-sports — live sports & TV broadcast streams
 *
 * Types:
 *   embed   — has a TMDB-compatible embed URL (played inline via WebView)
 *   scraper — HTML scraper / download indexer (background fallback)
 *   reader  — manga image reader (different UI paradigm)
 *   live    — live-stream portal (opened as WebView embed)
 */

export type SourceCategory = "movies" | "anime" | "manga" | "live-sports";
export type SourceType = "embed" | "scraper" | "reader" | "live";

export interface SourceEntry {
  id: string;
  name: string;
  domain: string;
  homeUrl: string;
  categories: SourceCategory[];
  type: SourceType;
  indieFriendly?: boolean;
  embedMovie?: (tmdbId: number) => string;
  embedTV?: (tmdbId: number, season: number, episode: number) => string;
}

// ─── Movies & TV Shows ────────────────────────────────────────────────────────
const MOVIE_SOURCES: SourceEntry[] = [
  {
    id: "vegamovies",
    name: "VegaMovies",
    domain: "vegamovies.mq",
    homeUrl: "https://vegamovies.mq/",
    categories: ["movies"],
    type: "scraper",
    indieFriendly: true,
  },
  {
    id: "1flex",
    name: "1Flex",
    domain: "www.1flex.org",
    homeUrl: "https://www.1flex.org/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://www.1flex.org/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://www.1flex.org/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "1shows",
    name: "1Shows",
    domain: "www.1shows.org",
    homeUrl: "https://www.1shows.org/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://www.1shows.org/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://www.1shows.org/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "1tube",
    name: "1Tube",
    domain: "www.1tube.org",
    homeUrl: "https://www.1tube.org/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://www.1tube.org/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://www.1tube.org/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "hdtoday",
    name: "HDToday",
    domain: "hdtodayz.net",
    homeUrl: "https://hdtodayz.net/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://hdtodayz.net/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://hdtodayz.net/embed/tv/${id}/${s}/${e}`,
    indieFriendly: true,
  },
  {
    id: "cineby",
    name: "Cineby",
    domain: "www.cineby.sc",
    homeUrl: "https://www.cineby.sc/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://www.cineby.sc/movie/${id}`,
    embedTV: (id, s, e) => `https://www.cineby.sc/tv/${id}?season=${s}&episode=${e}`,
    indieFriendly: true,
  },
  {
    id: "cinemabz",
    name: "Cinema.BZ",
    domain: "cinema.bz",
    homeUrl: "https://cinema.bz/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://cinema.bz/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://cinema.bz/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "filmcave",
    name: "FilmCave",
    domain: "filmcave.ru",
    homeUrl: "https://filmcave.ru/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://filmcave.ru/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://filmcave.ru/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "cinezo",
    name: "Cinezo",
    domain: "www.cinezo.net",
    homeUrl: "https://www.cinezo.net/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://www.cinezo.net/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://www.cinezo.net/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "streamex",
    name: "StreameX",
    domain: "streamex.sh",
    homeUrl: "https://streamex.sh/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://streamex.sh/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://streamex.sh/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "donkey",
    name: "Donkey",
    domain: "donkey.to",
    homeUrl: "https://donkey.to/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://donkey.to/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://donkey.to/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "sflix",
    name: "SFlix",
    domain: "sflix.fi",
    homeUrl: "https://sflix.fi/home",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://sflix.fi/movie/${id}`,
    embedTV: (id, s, e) => `https://sflix.fi/tv/${id}/${s}/${e}`,
  },
  {
    id: "fmovies",
    name: "FMovies",
    domain: "fmovies-hd.to",
    homeUrl: "https://fmovies-hd.to/home/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://fmovies-hd.to/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://fmovies-hd.to/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "smashystream",
    name: "SmashyStream",
    domain: "smashystream.xyz",
    homeUrl: "https://smashystream.xyz/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://embed.smashystream.com/playere.php?tmdb=${id}`,
    embedTV: (id, s, e) => `https://embed.smashystream.com/playere.php?tmdb=${id}&season=${s}&episode=${e}`,
    indieFriendly: true,
  },
  {
    id: "shuttletv",
    name: "ShuttleTV",
    domain: "shuttletv.su",
    homeUrl: "https://shuttletv.su/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://shuttletv.su/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://shuttletv.su/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "flickystream",
    name: "FlickyStream",
    domain: "flickystream.ru",
    homeUrl: "https://flickystream.ru/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://flickystream.ru/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://flickystream.ru/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "rivestream",
    name: "RiveStream",
    domain: "rivestream.ru",
    homeUrl: "https://rivestream.ru/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://rivestream.ru/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://rivestream.ru/embed/tv/${id}/${s}/${e}`,
    indieFriendly: true,
  },
  {
    id: "watchspencerdevs",
    name: "Spencer Watch",
    domain: "watch.spencerdevs.xyz",
    homeUrl: "https://watch.spencerdevs.xyz/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://watch.spencerdevs.xyz/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://watch.spencerdevs.xyz/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "cinegram",
    name: "Cinegram",
    domain: "cinegram.tv",
    homeUrl: "https://cinegram.tv/home",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://cinegram.tv/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://cinegram.tv/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "bcine",
    name: "BCine",
    domain: "bcine.app",
    homeUrl: "https://bcine.app/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://bcine.app/movie/${id}`,
    embedTV: (id, s, e) => `https://bcine.app/tv/${id}/${s}/${e}`,
  },
  {
    id: "willowmovies",
    name: "WillowMovies",
    domain: "willowmovies.com",
    homeUrl: "https://willowmovies.com/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://willowmovies.com/movie/${id}`,
    embedTV: (id, s, e) => `https://willowmovies.com/tv/${id}/${s}/${e}`,
  },
  {
    id: "nepu",
    name: "Nepu",
    domain: "nepu.to",
    homeUrl: "https://nepu.to/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://nepu.to/embed/movie?tmdb=${id}`,
    embedTV: (id, s, e) => `https://nepu.to/embed/tv?tmdb=${id}&season=${s}&episode=${e}`,
    indieFriendly: true,
  },
  {
    id: "67movies",
    name: "67Movies",
    domain: "67movies.net",
    homeUrl: "https://67movies.net/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://67movies.net/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://67movies.net/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "xprime",
    name: "XPrime",
    domain: "xprime.stream",
    homeUrl: "https://xprime.stream/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://xprime.stream/movie/${id}`,
    embedTV: (id, s, e) => `https://xprime.stream/tv/${id}/${s}/${e}`,
  },
  {
    id: "flixway",
    name: "FlixWay",
    domain: "flixway.ru",
    homeUrl: "https://flixway.ru/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://flixway.ru/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://flixway.ru/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "watchott",
    name: "WatchOTT",
    domain: "watchott.ru",
    homeUrl: "https://watchott.ru/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://watchott.ru/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://watchott.ru/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "watchott-disney",
    name: "Disney+ via WatchOTT",
    domain: "ds.watchott.ru",
    homeUrl: "https://ds.watchott.ru/originals/disney",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://ds.watchott.ru/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://ds.watchott.ru/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "watchott-netflix",
    name: "Netflix via WatchOTT",
    domain: "nf.watchott.ru",
    homeUrl: "https://nf.watchott.ru/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://nf.watchott.ru/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://nf.watchott.ru/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "cinebytv",
    name: "CinebyTV",
    domain: "cinebytv.com",
    homeUrl: "https://cinebytv.com/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://cinebytv.com/movie/${id}`,
    embedTV: (id, s, e) => `https://cinebytv.com/tv/${id}/${s}/${e}`,
  },
  // ─── Sources #107-109 from master list (user-verified) ───────────────────────
  {
    id: "123moviesrulz",
    name: "123MoviesRulz",
    domain: "123moviesrulz.online",
    homeUrl: "https://123moviesrulz.online/home/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://123moviesrulz.online/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://123moviesrulz.online/embed/tv/${id}/${s}/${e}`,
    indieFriendly: true,
  },
  {
    id: "xprimehub",
    name: "XPrimeHub",
    domain: "xprimehub.hair",
    homeUrl: "https://xprimehub.hair/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://xprimehub.hair/movie/${id}`,
    embedTV: (id, s, e) => `https://xprimehub.hair/tv/${id}/${s}/${e}`,
    indieFriendly: true,
  },
  {
    id: "rogmovies",
    name: "RogMovies",
    domain: "rogmovies.cv",
    homeUrl: "https://rogmovies.cv/",
    categories: ["movies"],
    type: "scraper",
    indieFriendly: true,
  },
  {
    id: "fzmovies",
    name: "FZMovies",
    domain: "fzmovies.ng",
    homeUrl: "https://fzmovies.ng/",
    categories: ["movies"],
    type: "scraper",
    indieFriendly: true,
  },

  // ─── v7.0 additions ───────────────────────────────────────────────────────
  {
    id: "vidsrc-to",
    name: "VidSrc.to",
    domain: "vidsrc.to",
    homeUrl: "https://vidsrc.to/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://vidsrc.to/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://vidsrc.to/embed/tv/${id}/${s}/${e}`,
    indieFriendly: true,
  },
  {
    id: "vidsrc-me",
    name: "VidSrc.me",
    domain: "vidsrc.me",
    homeUrl: "https://vidsrc.me/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://vidsrc.me/embed/movie?tmdb=${id}`,
    embedTV: (id, s, e) => `https://vidsrc.me/embed/tv?tmdb=${id}&season=${s}&episode=${e}`,
    indieFriendly: true,
  },
  {
    id: "vidsrc-xyz",
    name: "VidSrc.xyz",
    domain: "vidsrc.xyz",
    homeUrl: "https://vidsrc.xyz/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://vidsrc.xyz/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://vidsrc.xyz/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "themoviebox",
    name: "TheMovieBox",
    domain: "themoviebox.org",
    homeUrl: "https://themoviebox.org/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://themoviebox.org/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://themoviebox.org/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "multiembed",
    name: "MultiEmbed",
    domain: "multiembed.mov",
    homeUrl: "https://multiembed.mov/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://multiembed.mov/directstream.php?video_id=${id}&tmdb=1`,
    embedTV: (id, s, e) => `https://multiembed.mov/directstream.php?video_id=${id}&tmdb=1&s=${s}&e=${e}`,
  },
  {
    id: "embed-su",
    name: "Embed.su",
    domain: "embed.su",
    homeUrl: "https://embed.su/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://embed.su/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://embed.su/embed/tv/${id}/${s}/${e}`,
    indieFriendly: true,
  },
  {
    id: "moviesapi",
    name: "MoviesAPI.club",
    domain: "moviesapi.club",
    homeUrl: "https://moviesapi.club/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://moviesapi.club/movie/${id}`,
    embedTV: (id, s, e) => `https://moviesapi.club/tv/${id}-${s}-${e}`,
    indieFriendly: true,
  },
  {
    id: "autoembed-co",
    name: "AutoEmbed.co",
    domain: "autoembed.co",
    homeUrl: "https://autoembed.co/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://autoembed.co/movie/tmdb/${id}`,
    embedTV: (id, s, e) => `https://autoembed.co/tv/tmdb/${id}-${s}-${e}`,
  },
  {
    id: "2embed",
    name: "2Embed.cc",
    domain: "www.2embed.cc",
    homeUrl: "https://www.2embed.cc/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://www.2embed.cc/embed/${id}`,
    embedTV: (id, s, e) => `https://www.2embed.cc/embedtv/${id}&s=${s}&e=${e}`,
  },
  {
    id: "flickystream-su",
    name: "FlickyStream SU",
    domain: "flickystream.su",
    homeUrl: "https://flickystream.su/",
    categories: ["movies"],
    type: "embed",
    embedMovie: (id) => `https://flickystream.su/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://flickystream.su/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: "vegamovies-navy",
    name: "VegaMovies Navy",
    domain: "vegamovies.navy",
    homeUrl: "https://vegamovies.navy/",
    categories: ["movies"],
    type: "scraper",
    indieFriendly: true,
  },
  {
    id: "hdhub4u",
    name: "HDHub4u",
    domain: "new3.hdhub4u.cl",
    homeUrl: "https://new3.hdhub4u.cl/",
    categories: ["movies"],
    type: "scraper",
    indieFriendly: true,
  },
  {
    id: "sonyliv",
    name: "SonyLIV",
    domain: "www.sonyliv.com",
    homeUrl: "https://www.sonyliv.com/",
    categories: ["movies"],
    type: "embed",
    indieFriendly: true,
  },
  {
    id: "viki",
    name: "Viki",
    domain: "www.viki.com",
    homeUrl: "https://www.viki.com/",
    categories: ["movies", "anime"],
    type: "embed",
  },
];

// ─── Anime ────────────────────────────────────────────────────────────────────
const ANIME_SOURCES: SourceEntry[] = [
  {
    id: "reanime",
    name: "ReAnime",
    domain: "reanime.to",
    homeUrl: "https://reanime.to/home",
    categories: ["anime"],
    type: "embed",
    embedTV: (id, s, e) => `https://reanime.to/embed/tv/${id}/${s}/${e}`,
    embedMovie: (id) => `https://reanime.to/embed/movie/${id}`,
  },
  {
    id: "anidap",
    name: "AniDap",
    domain: "anidap.se",
    homeUrl: "https://anidap.se/home",
    categories: ["anime"],
    type: "embed",
    embedTV: (id, s, e) => `https://anidap.se/embed/tv/${id}/${s}/${e}`,
    embedMovie: (id) => `https://anidap.se/embed/movie/${id}`,
  },
  {
    id: "animex",
    name: "AnimeX",
    domain: "animex.one",
    homeUrl: "https://animex.one/home",
    categories: ["anime"],
    type: "embed",
    embedTV: (id, s, e) => `https://animex.one/embed/tv/${id}/${s}/${e}`,
    embedMovie: (id) => `https://animex.one/embed/movie/${id}`,
  },
  {
    id: "1anime",
    name: "1Anime",
    domain: "1anime.app",
    homeUrl: "https://1anime.app/discover",
    categories: ["anime"],
    type: "embed",
    embedTV: (id, s, e) => `https://1anime.app/embed/tv/${id}/${s}/${e}`,
    embedMovie: (id) => `https://1anime.app/embed/movie/${id}`,
  },
  {
    id: "yenime",
    name: "Yenime",
    domain: "yenime.net",
    homeUrl: "https://yenime.net/",
    categories: ["anime"],
    type: "embed",
    embedTV: (id, s, e) => `https://yenime.net/embed/tv/${id}/${s}/${e}`,
    embedMovie: (id) => `https://yenime.net/embed/movie/${id}`,
  },
  {
    id: "animepahe",
    name: "AnimePahe",
    domain: "animepahe.pw",
    homeUrl: "https://animepahe.pw/",
    categories: ["anime"],
    type: "scraper",
    indieFriendly: true,
  },
  {
    id: "kaa",
    name: "KAA",
    domain: "kaa.lt",
    homeUrl: "https://kaa.lt/",
    categories: ["anime"],
    type: "embed",
    embedTV: (id, s, e) => `https://kaa.lt/embed/tv/${id}/${s}/${e}`,
    embedMovie: (id) => `https://kaa.lt/embed/movie/${id}`,
  },
  {
    id: "kickassanime",
    name: "KickassAnime",
    domain: "kickassanime.cx",
    homeUrl: "https://kickassanime.cx/",
    categories: ["anime"],
    type: "scraper",
  },
  {
    id: "fanime",
    name: "Fanime",
    domain: "fanime.tv",
    homeUrl: "https://fanime.tv/",
    categories: ["anime"],
    type: "embed",
    embedTV: (id, s, e) => `https://fanime.tv/embed/tv/${id}/${s}/${e}`,
    embedMovie: (id) => `https://fanime.tv/embed/movie/${id}`,
  },
  {
    id: "9anime",
    name: "9Anime",
    domain: "9anime.cl",
    homeUrl: "https://9anime.cl/",
    categories: ["anime"],
    type: "embed",
    embedTV: (id, s, e) => `https://9anime.cl/embed/tv/${id}/${s}/${e}`,
    embedMovie: (id) => `https://9anime.cl/embed/movie/${id}`,
    indieFriendly: true,
  },
  {
    id: "justanime",
    name: "JustAnime",
    domain: "justanime.to",
    homeUrl: "https://justanime.to/",
    categories: ["anime"],
    type: "embed",
    embedTV: (id, s, e) => `https://justanime.to/embed/tv/${id}/${s}/${e}`,
    embedMovie: (id) => `https://justanime.to/embed/movie/${id}`,
  },
  {
    id: "anikage",
    name: "AniKage",
    domain: "anikage.cc",
    homeUrl: "https://anikage.cc/home",
    categories: ["anime"],
    type: "embed",
    embedTV: (id, s, e) => `https://anikage.cc/embed/tv/${id}/${s}/${e}`,
    embedMovie: (id) => `https://anikage.cc/embed/movie/${id}`,
  },
  {
    id: "enma",
    name: "Enma",
    domain: "www.enma.lol",
    homeUrl: "https://www.enma.lol/home",
    categories: ["anime"],
    type: "embed",
    embedTV: (id, s, e) => `https://www.enma.lol/embed/tv/${id}/${s}/${e}`,
    embedMovie: (id) => `https://www.enma.lol/embed/movie/${id}`,
  },
  {
    id: "animenexus",
    name: "Anime Nexus",
    domain: "anime.nexus",
    homeUrl: "https://anime.nexus/",
    categories: ["anime"],
    type: "embed",
    embedTV: (id, s, e) => `https://anime.nexus/embed/tv/${id}/${s}/${e}`,
    embedMovie: (id) => `https://anime.nexus/embed/movie/${id}`,
  },
  {
    id: "miruro",
    name: "Miruro",
    domain: "www.miruro.to",
    homeUrl: "https://www.miruro.to/",
    categories: ["anime"],
    type: "embed",
    embedTV: (id, s, e) => `https://www.miruro.to/embed/tv/${id}/${s}/${e}`,
    embedMovie: (id) => `https://www.miruro.to/embed/movie/${id}`,
    indieFriendly: true,
  },
  {
    id: "anistream",
    name: "AniStream",
    domain: "anistream.one",
    homeUrl: "https://anistream.one/",
    categories: ["anime"],
    type: "embed",
    embedTV: (id, s, e) => `https://anistream.one/embed/tv/${id}/${s}/${e}`,
    embedMovie: (id) => `https://anistream.one/embed/movie/${id}`,
  },
  {
    id: "animetsu",
    name: "AnimeTsu",
    domain: "animetsu.bz",
    homeUrl: "https://animetsu.bz/",
    categories: ["anime"],
    type: "embed",
    embedTV: (id, s, e) => `https://animetsu.bz/embed/tv/${id}/${s}/${e}`,
    embedMovie: (id) => `https://animetsu.bz/embed/movie/${id}`,
  },
  {
    id: "animekai",
    name: "AnimeKai",
    domain: "animekai.to",
    homeUrl: "https://animekai.to/home",
    categories: ["anime"],
    type: "embed",
    embedMovie: (id) => `https://animekai.to/embed/movie/${id}`,
    embedTV: (id, s, e) => `https://animekai.to/embed/tv/${id}/${s}/${e}`,
    indieFriendly: true,
  },
  {
    id: "hianime",
    name: "HiAnime",
    domain: "hianime.cv",
    homeUrl: "https://hianime.cv/home/",
    categories: ["anime"],
    type: "embed",
    embedTV: (id, s, e) => `https://hianime.cv/embed/tv/${id}/${s}/${e}`,
    embedMovie: (id) => `https://hianime.cv/embed/movie/${id}`,
    indieFriendly: true,
  },
  {
    id: "voidanime",
    name: "VoidAnime",
    domain: "www.voidanime.tech",
    homeUrl: "https://www.voidanime.tech/home#/",
    categories: ["anime"],
    type: "embed",
    embedTV: (id, s, e) => `https://www.voidanime.tech/embed/tv/${id}/${s}/${e}`,
    embedMovie: (id) => `https://www.voidanime.tech/embed/movie/${id}`,
  },
  {
    id: "animesuge",
    name: "AnimeSuge",
    domain: "animesuge.cz",
    homeUrl: "https://animesuge.cz/",
    categories: ["anime"],
    type: "embed",
    embedTV: (id, s, e) => `https://animesuge.cz/embed/tv/${id}/${s}/${e}`,
    embedMovie: (id) => `https://animesuge.cz/embed/movie/${id}`,
  },
];

// ─── Manga / Comics ───────────────────────────────────────────────────────────
const MANGA_SOURCES: SourceEntry[] = [
  { id: "mangaball",    name: "MangaBall",        domain: "mangaball.net",       homeUrl: "https://mangaball.net/",                    categories: ["manga"], type: "reader" },
  { id: "kagane",       name: "Kagane",            domain: "kagane.org",          homeUrl: "https://kagane.org/",                       categories: ["manga"], type: "reader" },
  { id: "comick",       name: "Comick",            domain: "comick.dev",          homeUrl: "https://comick.dev/",                       categories: ["manga"], type: "reader" },
  { id: "qtoon",        name: "QToon",             domain: "qtoon.net",           homeUrl: "https://qtoon.net/",                        categories: ["manga"], type: "reader" },
  { id: "mangago",      name: "MangaGo",           domain: "mangago.me",          homeUrl: "https://mangago.me/",                       categories: ["manga"], type: "reader" },
  { id: "allmanga",     name: "AllManga",          domain: "allmanga.to",         homeUrl: "https://allmanga.to/manga?cty=ALL",         categories: ["manga"], type: "reader", indieFriendly: true },
  { id: "asurascans",   name: "AsuraScans",        domain: "asurascans.com",      homeUrl: "https://asurascans.com/",                   categories: ["manga"], type: "reader", indieFriendly: true },
  { id: "mangahub",     name: "MangaHub",          domain: "mangahub.io",         homeUrl: "https://mangahub.io/",                      categories: ["manga"], type: "reader" },
  { id: "mangakatana",  name: "MangaKatana",       domain: "mangakatana.com",     homeUrl: "https://mangakatana.com/",                  categories: ["manga"], type: "reader" },
  { id: "atsu",         name: "Atsu",              domain: "atsu.moe",            homeUrl: "https://atsu.moe/",                         categories: ["manga"], type: "reader" },
  { id: "onisaga",      name: "Onisaga",           domain: "onisaga.com",         homeUrl: "https://onisaga.com/home",                  categories: ["manga"], type: "reader" },
  { id: "comix",        name: "Comix",             domain: "comix.to",            homeUrl: "https://comix.to/",                         categories: ["manga"], type: "reader" },
  { id: "mangadex",     name: "MangaDex",          domain: "mangadex.org",        homeUrl: "https://mangadex.org/",                     categories: ["manga"], type: "reader", indieFriendly: true },
  { id: "mangafire",    name: "MangaFire",         domain: "mangafire.to",        homeUrl: "https://mangafire.to/home",                 categories: ["manga"], type: "reader", indieFriendly: true },
  { id: "mangakakalot", name: "MangaKakalot",      domain: "www.mangakakalot.gg", homeUrl: "https://www.mangakakalot.gg/",              categories: ["manga"], type: "reader" },
  { id: "readcomic",    name: "ReadComicOnline",   domain: "readcomiconline.li",  homeUrl: "https://readcomiconline.li/",               categories: ["manga"], type: "reader" },
  { id: "weebcentral",  name: "WeebCentral",       domain: "weebcentral.com",     homeUrl: "https://weebcentral.com/",                  categories: ["manga"], type: "reader", indieFriendly: true },
  { id: "likemanga",    name: "LikeManga",         domain: "likemanga.ink",       homeUrl: "https://likemanga.ink/",                    categories: ["manga"], type: "reader" },
];

// ─── Live Sports ──────────────────────────────────────────────────────────────
const LIVE_SPORTS_SOURCES: SourceEntry[] = [
  {
    id: "tv247",
    name: "TV247",
    domain: "tv247.us",
    homeUrl: "https://tv247.us/",
    categories: ["live-sports"],
    type: "live",
    indieFriendly: true,
  },
  {
    id: "ntv",
    name: "NTV Live",
    domain: "ntv.cx",
    homeUrl: "https://ntv.cx/",
    categories: ["live-sports"],
    type: "live",
  },
  {
    id: "sportplus",
    name: "SportPlus",
    domain: "en12.sportplus.live",
    homeUrl: "https://en12.sportplus.live/",
    categories: ["live-sports"],
    type: "live",
    indieFriendly: true,
  },
  {
    id: "istreameast",
    name: "iStreamEast",
    domain: "istreameast.app",
    homeUrl: "https://istreameast.app/v52",
    categories: ["live-sports"],
    type: "live",
    indieFriendly: true,
  },
  {
    id: "famelack",
    name: "FameLack",
    domain: "famelack.com",
    homeUrl: "https://famelack.com/",
    categories: ["live-sports"],
    type: "live",
  },
  {
    id: "rivestream-sports",
    name: "RiveStream Sports",
    domain: "rivestream.ru",
    homeUrl: "https://rivestream.ru/livesports",
    categories: ["live-sports"],
    type: "live",
    indieFriendly: true,
  },
  {
    id: "beststreameast",
    name: "BestStreamEast",
    domain: "beststreameast.net",
    homeUrl: "https://beststreameast.net/",
    categories: ["live-sports"],
    type: "live",
  },
  {
    id: "tbcpl",
    name: "TBCPL",
    domain: "tbcpl.lol",
    homeUrl: "https://tbcpl.lol/",
    categories: ["live-sports"],
    type: "live",
  },
];

// ─── Master catalog ───────────────────────────────────────────────────────────
export const ALL_SOURCES: SourceEntry[] = [
  ...MOVIE_SOURCES,
  ...ANIME_SOURCES,
  ...MANGA_SOURCES,
  ...LIVE_SPORTS_SOURCES,
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

export function getSourcesByCategory(cat: SourceCategory): SourceEntry[] {
  return ALL_SOURCES.filter((s) => s.categories.includes(cat));
}

export function getEmbedSources(cat?: SourceCategory): SourceEntry[] {
  return ALL_SOURCES.filter(
    (s) => s.type === "embed" && (!cat || s.categories.includes(cat)),
  );
}

export function getLiveSportsSources(): SourceEntry[] {
  return ALL_SOURCES.filter((s) => s.type === "live");
}

export function getMangaSources(): SourceEntry[] {
  return ALL_SOURCES.filter((s) => s.type === "reader");
}

export function buildEmbedUrls(
  tmdbId: number,
  mediaType: "movie" | "tv",
  season = 1,
  episode = 1,
  cat?: SourceCategory,
): Array<{ url: string; source: string; isEmbed: true }> {
  return getEmbedSources(cat)
    .filter((s) => (mediaType === "movie" ? !!s.embedMovie : !!s.embedTV))
    .map((s) => ({
      url:
        mediaType === "movie"
          ? s.embedMovie!(tmdbId)
          : s.embedTV!(tmdbId, season, episode),
      source: s.name,
      isEmbed: true as const,
    }));
}

export const SOURCE_COUNT = ALL_SOURCES.length;
export const CATEGORY_COUNTS = {
  movies: getSourcesByCategory("movies").length,
  anime: getSourcesByCategory("anime").length,
  manga: getMangaSources().length,
  "live-sports": getLiveSportsSources().length,
};
